version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: travel_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  # Backend services
  user-service:
    build: ./backend/user_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_service:/app
    environment:
      - DB_HOST=postgres
      - DB_NAME=travel_db
      - DB_USER=user
      - DB_PASSWORD=password

    depends_on:
      - postgres
      - redis
  admin-service:
    build: ./backend/admin_service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/admin_service:/app
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/travel_db
      - DEBUG=true
    depends_on:
      - postgres
      - redis
  # booking-service:
  #   build: ./booking_service
  #   ports:
  #     - "8001:8001"
  # payment-service:
  #   build: ./payment_service
  #   ports:
  #     - "8002:8002"

  # Frontend service (React or Next.js app)
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - user-service

  # admin:
  #   build: ./admin
  #   restart: always
  #   # volumes:
  #   #   - ./admin:/app
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - admin-service

  nginx:
    image: nginx:latest
    container_name: travelhelper-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - admin-service
      - user-service
volumes:
  postgres_data:
