# Generated by Django 4.2.20 on 2025-04-07 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('trip_id', models.IntegerField()),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Cancelled'), ('4', 'Completed')], default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_date'],
            },
        ),
    ]
