# Generated by Django 4.2.20 on 2025-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(1, 'Захиалсан'), (2, 'Баталгаажсан'), (3, 'Цуцлагдсан')], default='1', max_length=20),
        ),
    ]
