# Generated by Django 4.2.20 on 2025-04-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 1), ('APPROVED', 2), ('CANCELED', 3)], default='1', max_length=20),
        ),
    ]
