# Generated by Django 4.2.20 on 2025-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
