# Generated by Django 4.2.20 on 2025-04-08 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_people_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.IntegerField()),
                ('people_count', models.IntegerField(default=1)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_camps', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('booking_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='booking.bookingcamp')),
            ],
        ),
    ]
