# Generated by Django 4.2.20 on 2025-03-25 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_delete_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=15),
        ),
    ]
