# Generated by Django 4.2.20 on 2025-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_user',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
