# Generated by Django 4.2.20 on 2025-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_trip_created_user_trip_created_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default=None, upload_to='trip/'),
            preserve_default=False,
        ),
    ]
