# Generated by Django 4.2.20 on 2025-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='capacity',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
